### ISSUE TITLE
Exploder doesn't explode on USD Composer

### ISSUE THREAD

**Issue by matbun** [syntway/model_exploder#1]
Dear Syntway developers, thank you for this extension. It exactly what I was looking for although... it does not seem to work on USD Composer 2023.2.1. As you can see from the screenshot below, to replicate the error you can import a simple NVIDIA-provided asset from the catalogue. After selecting all the parts of the object and activating the exploded view, nothing moves, not even after moving the center or changing the settings.

![Omniverse model exploder 1](https://github.com/syntway/model_exploder/assets/48362942/7733066c-adcc-441c-a15d-78aa62654b24)

From the console I can see this error repeating multiple times while moving the center of the explosion, which most likely is also the root cause of the problem:

```
2024-03-14 16:25:45 [801,840ms] [Error] [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1781' coro=<Engine._async_apply() done, defined at /home/jdoe2/Omniverse_extensions/model_exploder/exts/syntway.model_exploder/syntway/model_exploder/engine.py:358> exception=AttributeError("module 'pxr.Sdf' has no attribute 'BeginChangeBlock'")>
Traceback (most recent call last):
  File "/home/jdoe2/Omniverse_extensions/model_exploder/exts/syntway.model_exploder/syntway/model_exploder/engine.py", line 359, in _async_apply
    self._apply(dist_value, explo_center, meshes)
  File "/home/jdoe2/Omniverse_extensions/model_exploder/exts/syntway.model_exploder/syntway/model_exploder/engine.py", line 380, in _apply
    Engine.apply_state(state, self.usd.stage, self)
  File "/home/jdoe2/Omniverse_extensions/model_exploder/exts/syntway.model_exploder/syntway/model_exploder/engine.py", line 485, in apply_state
    Sdf.BeginChangeBlock()
AttributeError: module 'pxr.Sdf' has no attribute 'BeginChangeBlock'
```

May I kindly ask you some help with this, please? It is a pity that this extension is not working anymore!

Many thanks.

**Comment by syntway** [comment]
@matbun, thank you for reporting this problem. Release 0.9.5 contains a fix:
https://github.com/syntway/model_exploder/releases/tag/v0.9.5

You might need to download the release zip as it can take a while for the release to appear in Omniverse's Extensions window.
